[package]
authors = ["Ockam Developers"]
description = """Ockam is a library for building devices that communicate securely, privately
and trustfully with cloud services and other devices.
"""
edition = "2018"
exclude = [
    "tests/**"
]
homepage = "https://www.ockam.io/"
keywords = []
license = "Apache-2.0"
name = "ockam"
readme = "README.md"
repository = "https://github.com/ockam-network/ockam"
version = "0.1.0"

[features]
default = ["std"]
std = ["ockam_node"]

[dependencies]
ockam_core = {path = "../ockam_core", version = "0.2.0"}
ockam_node = {path = "../ockam_node", version = "0.1.2", optional = true}
ockam_node_attribute = {path = "../ockam_node_attribute", version = "0.1.3"}
hex = "0.4"
hashbrown = "0.9.1"

[dev-dependencies]
trybuild = {version = "1.0.38", features = ["diff"]}
