name: cargo_update_check
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  cargo_update_check:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:3d41b8e711888f2525b786f7751016eca0770f65c3f925909e2c1db45c8c0714
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Update and Check Ockam Example
        working-directory: examples/rust/get_started
        run: |
          rm -rf Cargo.lock
          cargo update
          cargo check
