name: Check CLA
on:
  pull_request:
    types: [opened]
jobs:
  check-submitter-for-cla:
    if: github.repository_owner == 'ockam-network'
    name: Check Submitter For CLA

    env:
      MESSAGE: "Yay! thanks for contributing to the Ockam repository @${{ github.actor }}. We are glad to see more contributors contributing to this open source origanization.\\n
      Do you mind signing our CLA by creating a pull request, adding your name to the [contributors.csv file](https://github.com/ockam-network/contributors/blob/main/CONTRIBUTORS.csv).\\n
      Please feel free to @mrinalwadhwa if you encounter any issue ❤️."

    environment:
      name: contributors
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Contributors
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          repository: ockam-network/contributors
          path: contributors

      # Gather necessary information
      - name: Setup
        run: |
          USER=${{ github.actor }}

          # Export variable
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
          echo "USER=$USER" >> $GITHUB_ENV

      - name: Check Submitter
        continue-on-error: true
        shell: bash
        run: |
          # Below attempt is to prevent following situation
          # https://github.community/t/github-actions-using-grep-when-no-lines-selected/126719
          CVS_USER=$(grep --max-count=1 --only-matching ${{ env.USER }} contributors/CONTRIBUTORS.csv || echo '<MISSING>')

          if [[ "$CVS_USER" == "<MISSING>" ]]
          then
            echo "CLA_NOT_SIGNED=1" >> $GITHUB_ENV
          else
            echo "INFO: User $USER signed the CLA"
            echo "CLA_NOT_SIGNED=0" >> $GITHUB_ENV
          fi

      - name: Create Comment
        if: env.CLA_NOT_SIGNED && env.CLA_NOT_SIGNED == 1
        run: |
          curl -s -H "Authorization: token ${{ secrets.CONTRIBUTORS_PAT }}" \
            -X POST -d '{ "body": "${{ env.MESSAGE }}" }' \
            "https://api.github.com/repos/ockam-network/ockam/issues/${{ github.event.issue.number }}/comments"
