name: docker_hub
on:
  workflow_dispatch:
  push:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'tools/docker/hub/**'
      - 'implementations/elixir/ockam/ockam_vault_software/**'
      - 'implementations/elixir/ockam/ockam/**'
      - 'implementations/elixir/ockam/ockam_kafka/**'
      - 'implementations/elixir/ockam/ockam_hub/**'

jobs:
  docker_hub:
    if: github.event.ref == 'refs/heads/develop' && github.repository_owner == 'ockam-network'
    runs-on: ubuntu-20.04
    environment:
      name: artifacts
    steps:
      - name: Repository Dispatch To Dev Builder
        uses: peter-evans/repository-dispatch@a3b37769d28120b0a633f6985f454bbc6293c946
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          repository: ockam-network/ockam_node_release
          event-type: hub_dev_builder
          client-payload: '{"sha": "${{ github.sha }}"}'
