name: hello_example_runner
on:
  workflow_dispatch:
  push:

jobs:
  std:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e382c8800a89ce43acb675131d9f30e74093d195a95047f87e9206a0c52c17a7
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: run Ockam on std
        working-directory: implementations/rust/ockam/ockam_examples/example_projects/no_std
        run: make example=hello std

      - name: run Ockam on no_std
        working-directory: implementations/rust/ockam/ockam_examples/example_projects/no_std
        run: make example=hello no_std

  emulators:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Install Qemu System ARM
        run: |
          sudo apt update
          sudo apt install qemu-system-arm

      - name: run Ockam on emulator
        working-directory: implementations/rust/ockam/ockam_examples/example_projects/no_std
        run: |
          rustup install nightly
          rustup target add thumbv7em-none-eabihf --toolchain nightly
          make example=hello qemu
