name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Check spelling
        uses: crate-ci/typos@0d9e0c2c1bd7f770f6eb90f87780848ca02fc12c
        with:
          config: tools/typos/typos.toml
